### ISSUE TITLE
Indicate img elements that don't have alt attribute

### ISSUE THREAD

**Issue by phuocng** [phuoc-ng/frontend-tips#7]
Give a red outline to any img having a missing or blank alt attribute:

```css
img:not([alt]),
img[alt=""] {
    outline: 8px solid red;
}
```

If you are using Visual Studio Code, you can install the webhint extension. It will automatically detect the issue and show the details when you hover on the element.

![image](https://user-images.githubusercontent.com/57786711/108662590-42bc8400-7501-11eb-8998-4827aea3e73b.png)
